scenario: scenarios.example_turtlesim

agent:
  namespaces: "/turtle1"
  behavior_tree_xml: "default_bt.xml"

bt_runner:
  bt_tick_rate: 10.0 
  bt_visualiser:
    enabled: True       # Set to True to enable BT visualisation, False to disable
    screen_width: 600 
    screen_height: 600 
  profiling_mode: False