scenario: scenarios.nav2_webots

agent:
  namespaces: ""              # 네임스페이스 없으면 "/" 유지
  behavior_tree_xml: "default_bt.xml"

bt_runner:
  bt_tick_rate: 10.0

  bt_visualiser:
    enabled: True              # BT GUI 보고 싶으면 True
    screen_width: 600
    screen_height: 600

  profiling_mode: False
